/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistaCajero;

/**
 *
 * @author DIDIER TORRES
 */
public class Login extends javax.swing.JFrame {
    private Cuentas usuario = new Cuentas(null,null,0,null,null,null); 
    int opcion;
    /**
     * Creates new form Login
     */
    public Login(Cuentas usuario,int opcion) {
        initComponents();
        this.usuario = usuario;
        this.opcion = opcion;
        this.aviso.setText("Ingresa tu contraseña");
        this.ocultar.setVisible(false);
        this.CampoContrasenia.setEchoChar(('*'));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        CampoContrasenia = new javax.swing.JPasswordField();
        Btn1 = new javax.swing.JButton();
        Btn2 = new javax.swing.JButton();
        Btn3 = new javax.swing.JButton();
        Btn5 = new javax.swing.JButton();
        Btn6 = new javax.swing.JButton();
        Btn4 = new javax.swing.JButton();
        Btn8 = new javax.swing.JButton();
        Btn9 = new javax.swing.JButton();
        Btn7 = new javax.swing.JButton();
        Log = new javax.swing.JButton();
        Btn0 = new javax.swing.JButton();
        Erase = new javax.swing.JButton();
        aviso = new javax.swing.JLabel();
        ocultar = new javax.swing.JLabel();
        mostrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setForeground(new java.awt.Color(51, 51, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe Script", 0, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/LOGOCAJERO.png"))); // NOI18N
        jLabel2.setText("INGRESO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 70));

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CampoContrasenia.setEditable(false);
        CampoContrasenia.setBackground(new java.awt.Color(0, 204, 204));
        CampoContrasenia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CampoContrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoContraseniaActionPerformed(evt);
            }
        });
        jPanel3.add(CampoContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 39, 162, 56));

        Btn1.setBackground(new java.awt.Color(0, 153, 153));
        Btn1.setText("1");
        Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn1ActionPerformed(evt);
            }
        });
        jPanel3.add(Btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 107, 50, 54));

        Btn2.setBackground(new java.awt.Color(0, 153, 153));
        Btn2.setText("2");
        Btn2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Btn2StateChanged(evt);
            }
        });
        Btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn2ActionPerformed(evt);
            }
        });
        jPanel3.add(Btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 107, 50, 54));

        Btn3.setBackground(new java.awt.Color(0, 153, 153));
        Btn3.setText("3");
        Btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn3ActionPerformed(evt);
            }
        });
        jPanel3.add(Btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 107, 50, 54));

        Btn5.setBackground(new java.awt.Color(0, 153, 153));
        Btn5.setText("5");
        Btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn5ActionPerformed(evt);
            }
        });
        jPanel3.add(Btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 167, 50, 50));

        Btn6.setBackground(new java.awt.Color(0, 153, 153));
        Btn6.setText("6");
        Btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn6ActionPerformed(evt);
            }
        });
        jPanel3.add(Btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 167, 50, 50));

        Btn4.setBackground(new java.awt.Color(0, 153, 153));
        Btn4.setText("4");
        Btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn4ActionPerformed(evt);
            }
        });
        jPanel3.add(Btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 167, 50, 50));

        Btn8.setBackground(new java.awt.Color(0, 153, 153));
        Btn8.setText("8");
        Btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn8ActionPerformed(evt);
            }
        });
        jPanel3.add(Btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 223, 50, 50));

        Btn9.setBackground(new java.awt.Color(0, 153, 153));
        Btn9.setText("9");
        Btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn9ActionPerformed(evt);
            }
        });
        jPanel3.add(Btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 223, 50, 50));

        Btn7.setBackground(new java.awt.Color(0, 153, 153));
        Btn7.setText("7");
        Btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn7ActionPerformed(evt);
            }
        });
        jPanel3.add(Btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 223, 50, 50));

        Log.setBackground(new java.awt.Color(0, 153, 153));
        Log.setText("A");
        Log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogActionPerformed(evt);
            }
        });
        jPanel3.add(Log, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 279, 50, 50));

        Btn0.setBackground(new java.awt.Color(0, 153, 153));
        Btn0.setText("0");
        Btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn0ActionPerformed(evt);
            }
        });
        jPanel3.add(Btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 279, 50, 50));

        Erase.setBackground(new java.awt.Color(0, 153, 153));
        Erase.setText("C");
        Erase.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                EraseComponentRemoved(evt);
            }
        });
        Erase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EraseActionPerformed(evt);
            }
        });
        jPanel3.add(Erase, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 279, 50, 50));

        aviso.setFont(new java.awt.Font("Segoe Script", 0, 12)); // NOI18N
        aviso.setText("ingresa tu contraseña");
        jPanel3.add(aviso, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 240, -1));

        ocultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icono_ocultar.png"))); // NOI18N
        ocultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ocultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ocultarMouseClicked(evt);
            }
        });
        jPanel3.add(ocultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 61, -1));

        mostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icono_ver.png"))); // NOI18N
        mostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostrarMouseClicked(evt);
            }
        });
        jPanel3.add(mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 39, -1, 56));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 290, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn0ActionPerformed
        if(this.CampoContrasenia.getText().length() >= 4){
            this.aviso.setText("EL LIMITE DE NUMEROS ES 4");
        }else{
            this.CampoContrasenia.setText(this.CampoContrasenia.getText() + "0");
        }
    }//GEN-LAST:event_Btn0ActionPerformed

    private void Btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn9ActionPerformed
        if(this.CampoContrasenia.getText().length() >= 4){
            this.aviso.setText("EL LIMITE DE NUMEROS ES 4");
        }else{
            this.CampoContrasenia.setText(this.CampoContrasenia.getText() + "9");
        }
    }//GEN-LAST:event_Btn9ActionPerformed

    private void EraseComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_EraseComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_EraseComponentRemoved

    private void CampoContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoContraseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoContraseniaActionPerformed

    private void Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn1ActionPerformed
        if(this.CampoContrasenia.getText().length() >= 4){
            this.aviso.setText("EL LIMITE DE NUMEROS ES 4");
        }else{
            this.CampoContrasenia.setText(this.CampoContrasenia.getText() + 1);
        }
    }//GEN-LAST:event_Btn1ActionPerformed

    private void Btn2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Btn2StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn2StateChanged

    private void Btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn2ActionPerformed
        if(this.CampoContrasenia.getText().length() >= 4){
            this.aviso.setText("EL LIMITE DE NUMEROS ES 4");
        }else{
            this.CampoContrasenia.setText(this.CampoContrasenia.getText() + "2");
        }
    }//GEN-LAST:event_Btn2ActionPerformed

    private void LogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogActionPerformed
        
        if(this.opcion == 1){
            
            if(this.CampoContrasenia.getText().equals(this.usuario.contrasenia)){
                PantallaCajero iteracion = new PantallaCajero(this.usuario);
                iteracion.setVisible(true);
                iteracion.setLocationRelativeTo(null);
                this.dispose();
            }else{
                this.aviso.setText("Contraseña incorrecta");
                this.CampoContrasenia.setText("");
            }
        }else if (opcion == 0){
            if(this.CampoContrasenia.getText().equals(this.usuario.contrasenia)){
                PantallaContraseña cambio = new PantallaContraseña(this.usuario);
            
                cambio.setVisible(true);
                cambio.setLocationRelativeTo(null);
                this.dispose();
            }else{
                this.aviso.setText("Contraseña incorrecta");
                this.CampoContrasenia.setText("");
            }
                
        }
    }//GEN-LAST:event_LogActionPerformed

    private void Btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn3ActionPerformed
        if(this.CampoContrasenia.getText().length() >= 4){
            this.aviso.setText("EL LIMITE DE NUMEROS ES 4");
        }else{
            this.CampoContrasenia.setText(this.CampoContrasenia.getText() + "3");
        }
    }//GEN-LAST:event_Btn3ActionPerformed

    private void Btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn4ActionPerformed
        if(this.CampoContrasenia.getText().length() >= 4){
            this.aviso.setText("EL LIMITE DE NUMEROS ES 4");
        }else{
            this.CampoContrasenia.setText(this.CampoContrasenia.getText() + "4");
        }
    }//GEN-LAST:event_Btn4ActionPerformed

    private void Btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn5ActionPerformed
        if(this.CampoContrasenia.getText().length() >= 4){
            this.aviso.setText("EL LIMITE DE NUMEROS ES 4");
        }else{
            this.CampoContrasenia.setText(this.CampoContrasenia.getText() + "5");
        }
    }//GEN-LAST:event_Btn5ActionPerformed

    private void Btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn6ActionPerformed
        if(this.CampoContrasenia.getText().length() >= 4){
            this.aviso.setText("EL LIMITE DE NUMEROS ES 4");
        }else{
            this.CampoContrasenia.setText(this.CampoContrasenia.getText() + "6");
        }
    }//GEN-LAST:event_Btn6ActionPerformed

    private void Btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn7ActionPerformed
        if(this.CampoContrasenia.getText().length() >= 4){
            this.aviso.setText("EL LIMITE DE NUMEROS ES 4");
        }else{
            this.CampoContrasenia.setText(this.CampoContrasenia.getText() + "7");
        }
    }//GEN-LAST:event_Btn7ActionPerformed

    private void Btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn8ActionPerformed
        if(this.CampoContrasenia.getText().length() >= 4){
            this.aviso.setText("EL LIMITE DE NUMEROS ES 4");
        }else{
            this.CampoContrasenia.setText(this.CampoContrasenia.getText() + "8");
        }
    }//GEN-LAST:event_Btn8ActionPerformed

    private void EraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EraseActionPerformed
        String currentText = this.CampoContrasenia.getText();
        if (!currentText.isEmpty()) {
            this.CampoContrasenia.setText(currentText.substring(0, currentText.length() - 1));
        }
    }//GEN-LAST:event_EraseActionPerformed

    private void ocultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ocultarMouseClicked
        this.ocultar.setVisible(false);
        this.mostrar.setVisible(true);
        this.CampoContrasenia.setEchoChar(('*'));
    }//GEN-LAST:event_ocultarMouseClicked

    private void mostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarMouseClicked
        this.mostrar.setVisible(false);
        this.ocultar.setVisible(true);
        this.CampoContrasenia.setEchoChar((char)0);
    }//GEN-LAST:event_mostrarMouseClicked
  
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn0;
    private javax.swing.JButton Btn1;
    private javax.swing.JButton Btn2;
    private javax.swing.JButton Btn3;
    private javax.swing.JButton Btn4;
    private javax.swing.JButton Btn5;
    private javax.swing.JButton Btn6;
    private javax.swing.JButton Btn7;
    private javax.swing.JButton Btn8;
    private javax.swing.JButton Btn9;
    private javax.swing.JPasswordField CampoContrasenia;
    private javax.swing.JButton Erase;
    private javax.swing.JButton Log;
    private javax.swing.JLabel aviso;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel mostrar;
    private javax.swing.JLabel ocultar;
    // End of variables declaration//GEN-END:variables
}
