/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistaCajero;

import java.awt.Color;

/**
 *
 * @author DIDIER TORRES
 */
public class PantallaInicio extends javax.swing.JFrame {

    /**
     * Creates new form PantallaInicio
     */
    private Cuentas usuario = new Cuentas(null,null,0,null,null,null); 
    
    public PantallaInicio(Cuentas usuario) {
        initComponents();
        this.usuario = usuario;
        this.avisoFallo.setText("");
        this.usuario.setMaxPrestamo(this.usuario.dinero * 3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        BtnIngreso = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        CampoTarjeta = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        campoApellido = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        avisoFallo = new javax.swing.JLabel();
        campoIdentidad = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 170, 10));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 170, 10));

        BtnIngreso.setFont(new java.awt.Font("Segoe Script", 0, 24)); // NOI18N
        BtnIngreso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnIngreso.setText("Ingresar -->");
        BtnIngreso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnIngreso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnIngresoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnIngresoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnIngresoMouseExited(evt);
            }
        });
        jPanel1.add(BtnIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, 260, 50));

        campoNombre.setBackground(new java.awt.Color(0, 255, 204));
        campoNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoNombre.setText("Ingrese su nombre");
        campoNombre.setBorder(null);
        campoNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoNombreMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                campoNombreMousePressed(evt);
            }
        });
        campoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreActionPerformed(evt);
            }
        });
        campoNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoNombreKeyTyped(evt);
            }
        });
        jPanel1.add(campoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 170, 30));

        CampoTarjeta.setBackground(new java.awt.Color(0, 255, 204));
        CampoTarjeta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CampoTarjeta.setText("Ingrese su tarjeta");
        CampoTarjeta.setBorder(null);
        CampoTarjeta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoTarjetaMouseClicked(evt);
            }
        });
        CampoTarjeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CampoTarjetaKeyTyped(evt);
            }
        });
        jPanel1.add(CampoTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 170, 30));

        jPanel2.setBackground(new java.awt.Color(255, 153, 102));

        jLabel2.setFont(new java.awt.Font("Segoe Script", 0, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/LOGOCAJERO.png"))); // NOI18N
        jLabel2.setText("Bienvenido... Cajero UD");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 90));

        campoApellido.setBackground(new java.awt.Color(0, 255, 204));
        campoApellido.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoApellido.setForeground(new java.awt.Color(51, 51, 0));
        campoApellido.setText("Ingrese sus apellidos");
        campoApellido.setBorder(null);
        campoApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                campoApellidoMousePressed(evt);
            }
        });
        campoApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoApellidoActionPerformed(evt);
            }
        });
        campoApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoApellidoKeyTyped(evt);
            }
        });
        jPanel1.add(campoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 170, 30));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 170, -1));

        avisoFallo.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        avisoFallo.setText("ingreso fallido");
        jPanel1.add(avisoFallo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 580, -1));

        campoIdentidad.setBackground(new java.awt.Color(0, 255, 204));
        campoIdentidad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoIdentidad.setText("Ingrese su cédula");
        campoIdentidad.setBorder(null);
        campoIdentidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoIdentidadMouseClicked(evt);
            }
        });
        campoIdentidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoIdentidadKeyTyped(evt);
            }
        });
        jPanel1.add(campoIdentidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 170, 30));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 170, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnIngresoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnIngresoMouseEntered
        this.BtnIngreso.setForeground(Color.white);
    }//GEN-LAST:event_BtnIngresoMouseEntered

    private void BtnIngresoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnIngresoMouseExited
        this.BtnIngreso.setForeground(Color.black);
    }//GEN-LAST:event_BtnIngresoMouseExited

    private void BtnIngresoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnIngresoMouseClicked
        
        
        if(this.CampoTarjeta.getText().equals(this.usuario.tarjeta) && !this.campoIdentidad.getText().equals("Ingrese su cédula") && !this.campoIdentidad.getText().equals("")){
            this.usuario.nombre = this.campoNombre.getText();
            this.usuario.apellido = this.campoApellido.getText();
            this.usuario.identidad = this.campoIdentidad.getText();
            
            Login ingreso = new Login(this.usuario,1);
            
            ingreso.setVisible(true);
            ingreso.setLocationRelativeTo(null);
            this.dispose();
        }else{
            this.avisoFallo.setText("Parece que hubo un error, ingresa nuevamente los datos");
        }
    }//GEN-LAST:event_BtnIngresoMouseClicked

    private void campoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreActionPerformed

    private void campoApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoApellidoActionPerformed

    private void campoNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoNombreMouseClicked
        
    }//GEN-LAST:event_campoNombreMouseClicked

    private void campoNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoNombreMousePressed
        if(this.campoNombre.getText().equals("Ingrese su nombre")){
            this.campoNombre.setText("");
        }
    }//GEN-LAST:event_campoNombreMousePressed

    private void campoApellidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoApellidoMousePressed
        if(this.campoApellido.getText().equals("Ingrese sus apellidos")){
            this.campoApellido.setText("");
        }
    }//GEN-LAST:event_campoApellidoMousePressed

    private void campoIdentidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoIdentidadMouseClicked
        if(this.campoIdentidad.getText().equals("Ingrese su cédula")){
            this.campoIdentidad.setText("");
        }
    }//GEN-LAST:event_campoIdentidadMouseClicked

    private void CampoTarjetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CampoTarjetaMouseClicked
        if(this.CampoTarjeta.getText().equals("Ingrese su tarjeta")){
            this.CampoTarjeta.setText("");
        }
    }//GEN-LAST:event_CampoTarjetaMouseClicked

    private void CampoTarjetaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoTarjetaKeyTyped
        
        if(this.CampoTarjeta.getText().equals("Ingrese su tarjeta")){
            this.CampoTarjeta.setText("");
        }
        
        if(this.CampoTarjeta.getText().length() >= 4){
            evt.consume();
        }else{
            char c = evt.getKeyChar();
            if (c < '0' || c > '9' ){
                evt.consume();
            }
        }
    }//GEN-LAST:event_CampoTarjetaKeyTyped

    private void campoIdentidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoIdentidadKeyTyped
        
        if(this.campoIdentidad.getText().equals("Ingrese su cédula")){
            this.campoIdentidad.setText("");
        }
        
        if(this.campoIdentidad.getText().length() >= 10){
            evt.consume();
        }else{
            char c = evt.getKeyChar();
            if (c < '0' || c > '9' ){
                evt.consume();
            }
        }
    }//GEN-LAST:event_campoIdentidadKeyTyped

    private void campoNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNombreKeyTyped
        
        if(this.campoNombre.getText().equals("Ingrese su nombre")){
            this.campoNombre.setText("");
        }
        
        char c = evt.getKeyChar();
        if (!Character.isLetter(c) && c != ' ') {
            evt.consume();
        }
    }//GEN-LAST:event_campoNombreKeyTyped

    private void campoApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoApellidoKeyTyped
        
        if(this.campoApellido.getText().equals("Ingrese sus apellidos")){
            this.campoApellido.setText("");
        }
        
        char c = evt.getKeyChar();
        if (!Character.isLetter(c) && c != ' ') {
            evt.consume();
        }
    }//GEN-LAST:event_campoApellidoKeyTyped

    /**
     * @param args the command line arguments
     */     
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnIngreso;
    private javax.swing.JTextField CampoTarjeta;
    private javax.swing.JLabel avisoFallo;
    private javax.swing.JTextField campoApellido;
    private javax.swing.JTextField campoIdentidad;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
    
}
