/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistaCajero;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author DIDIER TORRES
 */
public class Prestador extends javax.swing.JFrame {
    private Cuentas usuario = new Cuentas(null,null,0,null,null,null); 
    char c;
    
    /**
     * Creates new form Prestador
     */
    public Prestador(Cuentas ususario) {
        
        initComponents();
        this.usuario = ususario;
        this.fechaActual.setText("Fecha: " + this.usuario.fechaActual.toString());
        this.nombreUsuario.setText(this.usuario.nombre + " " + this.usuario.apellido);
        this.maximoPrestamo.setText("Máximo: " + Integer.toString(this.usuario.maxPrestamo));
        this.numeroPrestamo.setText("Prestamo # " + Integer.toString(this.usuario.totalPrestamos));
        this.fechaMaxima.setText("Fecha de pago: " + this.usuario.fechaActual.plusDays(30 * this.cuotasS.getValue()).toString());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        numeroPrestamo = new javax.swing.JLabel();
        sliderWarning = new javax.swing.JLabel();
        Identidad = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Celular = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        Telefono = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        valPrestamo = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        cuotasS = new javax.swing.JSlider();
        cuotasL = new javax.swing.JLabel();
        confirmacion = new javax.swing.JLabel();
        nombreUsuario = new javax.swing.JLabel();
        maximoPrestamo = new javax.swing.JLabel();
        fechaMaxima = new javax.swing.JLabel();
        fechaActual = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Segoe Script", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/LOGOCAJERO.png"))); // NOI18N
        jLabel1.setText("PEDIR PRESTAMOS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(21, 21, 21))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 120));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("POR FAVOR INGRESA LOS SIGUIENTES DATOS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 600, 50));

        numeroPrestamo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        numeroPrestamo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numeroPrestamo.setText("N prestamo");
        jPanel1.add(numeroPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 600, 60));

        sliderWarning.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sliderWarning.setText("Desliza para ajustar las cuotas de tu préstamo (Máximo 6 cuotas)");
        jPanel1.add(sliderWarning, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 520, 30));

        Identidad.setBackground(new java.awt.Color(102, 204, 255));
        Identidad.setText("No identidad");
        Identidad.setBorder(null);
        Identidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                IdentidadMousePressed(evt);
            }
        });
        Identidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                IdentidadKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IdentidadKeyTyped(evt);
            }
        });
        jPanel1.add(Identidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 340, 30));

        jSeparator1.setBackground(new java.awt.Color(102, 204, 255));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 340, 20));

        Celular.setBackground(new java.awt.Color(102, 204, 255));
        Celular.setText("No de celular");
        Celular.setBorder(null);
        Celular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CelularMousePressed(evt);
            }
        });
        Celular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CelularKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CelularKeyTyped(evt);
            }
        });
        jPanel1.add(Celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 340, 30));

        jSeparator2.setBackground(new java.awt.Color(102, 204, 255));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 340, 20));

        Telefono.setBackground(new java.awt.Color(102, 204, 255));
        Telefono.setText("No de teléfono ");
        Telefono.setBorder(null);
        Telefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TelefonoMousePressed(evt);
            }
        });
        Telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoActionPerformed(evt);
            }
        });
        Telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TelefonoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TelefonoKeyTyped(evt);
            }
        });
        jPanel1.add(Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 340, 30));

        jSeparator3.setBackground(new java.awt.Color(102, 204, 255));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 340, 20));

        valPrestamo.setBackground(new java.awt.Color(102, 204, 255));
        valPrestamo.setText("Valor del préstamo");
        valPrestamo.setBorder(null);
        valPrestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                valPrestamoMousePressed(evt);
            }
        });
        valPrestamo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                valPrestamoKeyTyped(evt);
            }
        });
        jPanel1.add(valPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 340, 30));

        jSeparator4.setBackground(new java.awt.Color(102, 204, 255));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 340, 20));

        jPanel3.setBackground(new java.awt.Color(102, 204, 255));

        cuotasS.setBackground(new java.awt.Color(102, 204, 255));
        cuotasS.setForeground(new java.awt.Color(204, 0, 0));
        cuotasS.setMajorTickSpacing(1);
        cuotasS.setMaximum(6);
        cuotasS.setMinimum(1);
        cuotasS.setPaintTicks(true);
        cuotasS.setPaintTrack(false);
        cuotasS.setToolTipText("");
        cuotasS.setValue(1);
        cuotasS.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cuotasSStateChanged(evt);
            }
        });

        cuotasL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cuotasL.setText("1 cuotas");

        confirmacion.setBackground(new java.awt.Color(255, 0, 204));
        confirmacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        confirmacion.setText("Avanzar -->");
        confirmacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        confirmacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmacionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                confirmacionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                confirmacionMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(cuotasS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cuotasL, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(confirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuotasS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuotasL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(confirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 600, 90));

        nombreUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nombreUsuario.setText("Nombre de usuario");
        jPanel1.add(nombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 340, 30));

        maximoPrestamo.setText("Valmáx");
        jPanel1.add(maximoPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 406, 170, 30));

        fechaMaxima.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fechaMaxima.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fechaMaxima.setText("jLabel5");
        jPanel1.add(fechaMaxima, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, 220, 40));

        fechaActual.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fechaActual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fechaActual.setText("jLabel5");
        jPanel1.add(fechaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 220, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cuotasSStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cuotasSStateChanged
        this.cuotasL.setText(Integer.toString(this.cuotasS.getValue()) + " Cuotas");
        this.fechaMaxima.setText("Fecha de pago" + this.usuario.fechaActual.plusDays(30 * this.cuotasS.getValue()).toString());
    }//GEN-LAST:event_cuotasSStateChanged

    private void confirmacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmacionMouseEntered
        this.confirmacion.setForeground(Color.white);
    }//GEN-LAST:event_confirmacionMouseEntered

    private void confirmacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmacionMouseExited
        this.confirmacion.setForeground(Color.black);
    }//GEN-LAST:event_confirmacionMouseExited

    private void CelularMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CelularMousePressed
        if(this.Celular.getText().equals("No de celular")){
            this.Celular.setText("");
        }
    }//GEN-LAST:event_CelularMousePressed

    private void TelefonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TelefonoMousePressed
        if(this.Telefono.getText().equals("No de teléfono ")){
            this.Telefono.setText("");
        }
    }//GEN-LAST:event_TelefonoMousePressed

    private void valPrestamoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_valPrestamoMousePressed
        if(this.valPrestamo.getText().equals("Valor del préstamo")){
            this.valPrestamo.setText("");
        }
    }//GEN-LAST:event_valPrestamoMousePressed

    private void confirmacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmacionMouseClicked
        
        Prestamos nuevoPrestamo = new Prestamos(this.usuario,0);
        nuevoPrestamo.setNumeroPrestamo(this.usuario.totalPrestamos);

        if (this.usuario.maxPrestamo > Integer.parseInt(this.valPrestamo.getText())){
            
            nuevoPrestamo.ingresarDinero(Integer.parseInt(this.valPrestamo.getText()));
            this.dispose();
            this.usuario.maxPrestamo = (this.usuario.maxPrestamo - Integer.parseInt(this.valPrestamo.getText()));
            JOptionPane.showMessageDialog(null, "Nombre: " + this.usuario.nombre + "\n" + "Apellidos: " + this.usuario.apellido + "\n" + "Documento número: " + this.Identidad.getText() + "\n" +"Numero de celular: " + this.Celular.getText()+ "\n" + "Numero de teléfono: " +this.Telefono.getText() + "\n" + "Valor de préstamo: " +  this.valPrestamo.getText() + "\n" + this.fechaActual.getText() + "     " +  this.fechaMaxima.getText());
            
            
        }else if(this.usuario.maxPrestamo < Integer.parseInt(this.valPrestamo.getText())){
            
            this.sliderWarning.setText("!No tienes pemitido un prestamo así de grande¡");
        }else{
            nuevoPrestamo.ingresarDinero(Integer.parseInt(this.valPrestamo.getText()));
            this.dispose();
            this.usuario.maxPrestamo = (this.usuario.maxPrestamo - Integer.parseInt(this.valPrestamo.getText()));
            JOptionPane.showMessageDialog(null, "Nombre: " + this.usuario.nombre + "\n" + "Apellidos: " + this.usuario.apellido + "\n" + "Documento número: " + this.Identidad.getText() + "\n" +"Numero de celular: " + this.Celular.getText()+ "\n" + "Numero de teléfono: " +this.Telefono.getText() + "\n" + "Valor de préstamo: " +  this.valPrestamo.getText() + "\n" + this.fechaActual.getText() + "     " +  this.fechaMaxima.getText());
            nuevoPrestamo.ingresarDinero(Integer.parseInt(this.valPrestamo.getText()));
        }
        
        
        
    }//GEN-LAST:event_confirmacionMouseClicked

    private void TelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonoActionPerformed

    private void valPrestamoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valPrestamoKeyTyped
        
        if(this.valPrestamo.getText().equals("Valor del préstamo")){
            this.valPrestamo.setText("");
        }
        
        if(valPrestamo.getText().length() >= 10){
            evt.consume();
        }else{
            char c = evt.getKeyChar();
            if (c < '0' || c > '9' ){
                evt.consume();
            }
        }
         
    }//GEN-LAST:event_valPrestamoKeyTyped

    private void TelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelefonoKeyPressed
        
    }//GEN-LAST:event_TelefonoKeyPressed

    private void CelularKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CelularKeyPressed
        
    }//GEN-LAST:event_CelularKeyPressed

    private void CelularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CelularKeyTyped
        
        if(this.Celular.getText().equals("No de celular")){
            this.Celular.setText("");
        }
        
        if(Celular.getText().length() >= 10){
            evt.consume();
        }else{
            char c = evt.getKeyChar();
            if (c < '0' || c > '9' ){
                evt.consume();
            }
        }
    }//GEN-LAST:event_CelularKeyTyped

    private void TelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelefonoKeyTyped
        
        if(this.Telefono.getText().equals("No de teléfono")){
            this.Telefono.setText("");
        }
        
        if(Telefono.getText().length() >= 10){
            evt.consume();
        }else{
            char c = evt.getKeyChar();
            if (c < '0' || c > '9' ){
                evt.consume();
            }
        }
    }//GEN-LAST:event_TelefonoKeyTyped

    private void IdentidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IdentidadKeyTyped

        if(this.Identidad.getText().equals("No identidad")){
            this.Identidad.setText("");
        }

        if(Identidad.getText().length() >= 10){
            evt.consume();
        }else{
            char c = evt.getKeyChar();
            if (c < '0' || c > '9' ){
                evt.consume();
            }
        }
    }//GEN-LAST:event_IdentidadKeyTyped

    private void IdentidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IdentidadKeyPressed

    }//GEN-LAST:event_IdentidadKeyPressed

    private void IdentidadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IdentidadMousePressed
        if(this.Identidad.getText().equals("No identidad")){
            this.Identidad.setText("");
        }
    }//GEN-LAST:event_IdentidadMousePressed

    /**
     * @param args the command line arguments
     */
       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Celular;
    private javax.swing.JTextField Identidad;
    private javax.swing.JTextField Telefono;
    private javax.swing.JLabel confirmacion;
    private javax.swing.JLabel cuotasL;
    private javax.swing.JSlider cuotasS;
    private javax.swing.JLabel fechaActual;
    private javax.swing.JLabel fechaMaxima;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel maximoPrestamo;
    private javax.swing.JLabel nombreUsuario;
    private javax.swing.JLabel numeroPrestamo;
    private javax.swing.JLabel sliderWarning;
    private javax.swing.JTextField valPrestamo;
    // End of variables declaration//GEN-END:variables
}
